Feature/consumoalimentar
Eddyosos/integracao201701 pull request #64
Opened 2017-05-24 19:36 UTC by eliezerdejj

2017-05-24 19:37 UTC, eliezerdejj commented
#23

2017-05-26 02:48 UTC, jorgetbruno requested changes
Faz o rebase para a master, seu projeto nem da build aqui.

2017-05-29 22:31 UTC, eliezerdejj commented
Foi feito o Rebase solicitado, e no que se refere as classes do tipo Enum, não há solução, #65

2017-05-29 22:44 UTC, jorgetbruno approved these changes

2017-05-29 22:45 UTC, jorgetbruno commented
issue #23

2017-05-29 22:46 UTC, merged