Feature/ficha consumo alimentar
Eddyosos/integracao201701 pull request #72
Opened 2017-06-23 13:07 UTC by eliezerdejj

2017-06-23 22:42 UTC, Eddyosos requested changes
Várias validações estão incoerentes.
Exemplo: PerguntasQuestionarioCriancasMenoresSeisMeses
observe as discrepâncias entre a função e o dicionário de dados

2017-06-24 03:05 UTC, eliezerdejj commented
As alterações foram, efetuadas 
As validações incoerentes foram corrigidas

2017-06-24 07:21 UTC, Eddyosos approved these changes

2017-06-24 07:24 UTC, Eddyosos commented
Considerando a urgência que estamos, este pull foi aprovado, tome nota que nele falta documentação e testes;
Ainda lembre de especificar qual Issue está sendo resolvida

2017-06-24 07:24 UTC, merged